feat: Adapt the app for the new Lenra API
lenra-io/app-camping-des-speakers pull request #38
Opened 2023-10-06 11:55 UTC by taorepoara

Closes #37 

## Description des modifications
Utiliser la lib @lenra/app plutôt que les anciennes libs et adapter l'application aux changements.

## Liste de contrôle
- [ ] Je n'ai pas surdimensionné ma PR
- [ ] Le titre de ma PR correspond à la [convention de commit](https://www.conventionalcommits.org/en/v1.0.0/)
- [ ] Je n'ai pas inclus de modifications majeures
- [ ] J'ai effectué ma propre relecture de code avant d'en demander une

### J'ai inclus des tests unitaires qui couvrent mes modifications
  - [ ] 👍 oui
  - [ ] 🙅 non, car ils ne sont pas nécessaires
  - [ ] 🙋 non, car j'ai besoin d'aide

### J'ai ajouté/mis à jour la documentation concernant mes modifications

- [ ] 📜 README.md
- [ ] 📕 docs/*.md
- [ ] 🙅 aucune documentation nécessaire

2023-10-07 19:24 UTC, jonas-martinez approved these changes
EDIT: Wrong PR

2023-10-07 19:26 UTC, jonas-martinez requested changes
my bad

2023-10-15 20:10 UTC, taorepoara commented
@jonas-martinez Can you look at this PR please?

2023-10-16 09:04 UTC, jonas-martinez approved these changes
LGTM

2023-10-16 09:05 UTC, merged